package com.myspace.loan_application;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Loan implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Amount")
	private int amount;
	private java.lang.Double intrestRate;
	private int duration;
	private java.lang.Boolean approved;

	public Loan() {
	}

	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	public java.lang.Double getIntrestRate() {
		return this.intrestRate;
	}

	public void setIntrestRate(java.lang.Double intrestRate) {
		this.intrestRate = intrestRate;
	}

	public int getDuration() {
		return this.duration;
	}

	public void setDuration(int duration) {
		this.duration = duration;
	}

	public java.lang.Boolean getApproved() {
		return this.approved;
	}

	public void setApproved(java.lang.Boolean approved) {
		this.approved = approved;
	}

	public Loan(int amount, java.lang.Double intrestRate, int duration,
			java.lang.Boolean approved) {
		this.amount = amount;
		this.intrestRate = intrestRate;
		this.duration = duration;
		this.approved = approved;
	}

}